language: node_js
os:
  - linux
  - osx
node_js:
  - "8"
  - "10"
matrix:
  exclude:
  - os: osx
    node_js: "8"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cairo pango ; fi
script:
  - yarn build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn lerna run --scope vega-scenegraph test    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn lerna run --ignore vega-scenegraph test ; fi
